### ISSUE TITLE
Problems with numbers shown for grades when hovering over %

### ISSUE THREAD

**Issue by gjkeller** [scorecardto/scorecard#6]
<img width="170" alt="image" src="https://user-images.githubusercontent.com/19877649/207375987-eab4451a-9c6e-49b0-9d70-c4fd5fb540d3.png">
This math doesn't add up -- this should be a 14.8/15 instead of 14/17, Scorecard is converting the grade to an integer and using the maximum value when its should be using the grade scale (see below for actual grade in Frontline)
<img width="1512" alt="Screenshot 2022-12-13 at 9 34 36 AM" src="https://user-images.githubusercontent.com/19877649/207376431-cdaf6206-96ac-4597-9988-99e0c5e9a91d.png">

**Comment by MaliciousFiles** [comment]
The maximum should be a relatively easy fix, when I first made it I couldn't remember which value it was supposed to use for maximum and never looked into it.

The converting to an integer may require updating the extension's fetching code, which would take some time.

**Comment by MaliciousFiles** [comment]
Displaying as an integer will be fixed when the extension is updated, but displaying the wrong maximum should now be fixed on the website.
